GET http://localhost:3001/user/create

###
PATCH  http://localhost:3001/user/e9c5bc38-c414-11ee-b76f-3a1a895bcf10
Content-Type: application/json

{
    "welcome_completed": true
}

###
GET  http://localhost:3001/user/e9c5bc38-c414-11ee-b76f-3a1a895bcf10

